# Generated by Django 4.2 on 2024-02-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название статьи')),
                ('date', models.DateField(verbose_name='Введите дату публикации')),
                ('anons', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Первичный текст статьи')),
                ('id_news', models.CharField(max_length=8, verbose_name='Напишите id новости')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
